"""
sync_threat_intel.py - single entrypoint that keeps Redis in sync with
both threat-intel sources:

  1. Bootstrap: if threat_data/full.csv doesn't exist yet, offers to
     download MalwareBazaar's full CSV export (served as a zip) and
     extract it there
  2. Live: pulls the last hour's samples from the MalwareBazaar API
  3. Bulk: loads full.csv into Redis

All three paths write through ONE function (_write_batch) using ONE
quoting rule (_q). Nothing else in this file adds or strips quotes.
tier1_bouncer.py's lookup format (malware:"<hash>" keys, quoted
family/reporter values) is left exactly as-is.
"""

import os
import sys
import csv
import socket
import zipfile
import urllib3.util.connection as urllib3_cn
import requests
import redis
from dotenv import load_dotenv
from tqdm import tqdm

# Force IPv4 - avoids slow/broken IPv6 routes some networks have to abuse.ch
def _allowed_gai_family():
    return socket.AF_INET
urllib3_cn.allowed_gai_family = _allowed_gai_family

load_dotenv()

MALWARE_BAZAAR_KEY = os.getenv("MALWARE_BAZAAR_KEY")
API_URL = "https://mb-api.abuse.ch/api/v1/"
SELECTOR = "time"  # last 60 minutes

# Full CSV export - a one-time bulk dataset, generated by MalwareBazaar
# at most once per hour, used only to seed Redis on a fresh setup.
# Served zip-compressed, so this is downloaded and extracted rather than
# saved directly.
FULL_CSV_EXPORT_URL_TEMPLATE = "https://mb-api.abuse.ch/v2/files/exports/{key}/full.csv.zip"

# Resolve relative to this file's location: dev checks/ -> logparser/threat_data/
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CSV_PATH = os.getenv(
    "THREAT_CSV_PATH",
    os.path.join(BASE_DIR, "..", "threat_data", "full.csv")
)
BATCH_SIZE = 5000

# Set when the launcher runs this script on its hourly schedule. In that
# mode the script must never wait for keyboard input.
NO_PROMPT = "--no-prompt" in sys.argv[1:]

r = redis.Redis(
    host="localhost",
    port=int(os.getenv("REDIS_DOCKER_PORT", "6379")),
    db=0,
    decode_responses=True,
)


def _redact(text):
    """Hides the API key in text that is about to be printed. The bulk
    export URL contains the key, and requests includes the URL in its
    error messages."""
    text = str(text)
    if MALWARE_BAZAAR_KEY:
        text = text.replace(MALWARE_BAZAAR_KEY, "<redacted>")
    return text


# ---------------------------------------------------------------------
# THE ONE PLACE QUOTING HAPPENS
# ---------------------------------------------------------------------
def _q(value, default="n/a"):
    """Wrap value in exactly one layer of literal double quotes, e.g.
    hash -> '"<hash>"'. Called on every value written to Redis, from
    both ingestion paths. Never call this twice on the same value."""
    value = (value or "").strip()
    if not value or value.lower() in ("n/a", "na", "none", "-", ""):
        value = default
    return f'"{value}"'


def _write_batch(batch):
    """batch: list of (sha256, family, reporter) tuples - all plain,
    unquoted strings. Quoting happens once, right here."""
    if not batch:
        return 0, 0

    quoted_hashes = [_q(sha) for sha, _, _ in batch]
    existing = r.smismember("malware:hashes", *quoted_hashes)

    pipe = r.pipeline()
    added = 0
    for (sha, family, reporter), qhash, already_have in zip(batch, quoted_hashes, existing):
        if already_have:
            continue
        added += 1
        pipe.sadd("malware:hashes", qhash)
        pipe.hset(f"malware:{qhash}", mapping={
            "family": _q(family, default="Unknown_Malware"),
            "reporter": _q(reporter, default="unknown"),
        })
        pipe.hset("known_bad_hashes", qhash, _q(family, default="Unknown_Malware"))
    pipe.execute()

    return added, len(batch) - added


# ---------------------------------------------------------------------
# STAGE 0 - BOOTSTRAP: download full.csv if it doesn't exist yet
# ---------------------------------------------------------------------
def _confirm_csv_bootstrap():
    print("\n[?] threat_data/full.csv was not found.")
    print("    This is a one-time bulk download (roughly 500 MB) of MalwareBazaar's")
    print("    full hash dataset, used to seed the local Redis threat-intel cache.")
    try:
        answer = input("    Download it now? [y/n]: ").strip().lower()
    except EOFError:
        return False  # no console attached - treat as a decline
    return answer == "y"


def _print_manual_csv_instructions():
    print("    Manual option: download the full CSV export yourself from")
    print("    https://bazaar.abuse.ch/export/ and save it as:")
    print(f"    {CSV_PATH}")


def stage_bootstrap_csv():
    """If threat_data/full.csv doesn't exist yet, offer to download
    MalwareBazaar's full CSV export (served as a zip) and extract it
    there. Runs once - after the file exists, this stage does nothing on
    every future run. Never blocks the rest of the script:
    stage_load_csv() already treats a missing CSV as optional, so a
    declined or failed download just means the live hourly sync is what
    populates Redis instead."""
    if os.path.exists(CSV_PATH):
        return

    if NO_PROMPT:
        print("[*] STAGE 0: full.csv not present, skipping bulk download "
              "(--no-prompt). Run this script manually to be offered it.")
        return

    print(f"[*] STAGE 0: {CSV_PATH} not found.")

    if not MALWARE_BAZAAR_KEY:
        print("[!] MALWARE_BAZAAR_KEY not set in .env - cannot download the bulk export.")
        _print_manual_csv_instructions()
        return

    if not _confirm_csv_bootstrap():
        print("[!] Skipped by user.")
        _print_manual_csv_instructions()
        return

    url = FULL_CSV_EXPORT_URL_TEMPLATE.format(key=MALWARE_BAZAAR_KEY)
    zip_path = CSV_PATH + ".zip.part"

    try:
        os.makedirs(os.path.dirname(CSV_PATH), exist_ok=True)

        with requests.get(url, stream=True, timeout=60) as response:
            response.raise_for_status()
            total = int(response.headers.get("content-length", 0))

            with open(zip_path, "wb") as f, tqdm(
                total=total, unit="B", unit_scale=True, desc="Downloading full.csv.zip"
            ) as bar:
                for chunk in response.iter_content(chunk_size=1024 * 1024):
                    if chunk:
                        f.write(chunk)
                        bar.update(len(chunk))

        print("[*] Extracting CSV from downloaded archive...")
        with zipfile.ZipFile(zip_path) as zf:
            # The archive is expected to contain exactly one CSV file.
            # Grab the first .csv member regardless of its internal name,
            # so this doesn't break if abuse.ch names it differently
            # inside the zip than the zip file itself is named.
            csv_members = [n for n in zf.namelist() if n.lower().endswith(".csv")]
            if not csv_members:
                raise ValueError("Downloaded archive did not contain a .csv file.")

            with zf.open(csv_members[0]) as src, open(CSV_PATH, "wb") as dst:
                dst.write(src.read())

        print(f"[+] Saved to {CSV_PATH}")

    except Exception as e:
        print(f"[!] Download or extraction failed: {_redact(e)}")
        if os.path.exists(CSV_PATH):
            os.remove(CSV_PATH)
        _print_manual_csv_instructions()

    finally:
        if os.path.exists(zip_path):
            os.remove(zip_path)


# ---------------------------------------------------------------------
# STAGE 1 - LIVE: MalwareBazaar "get_recent"
# ---------------------------------------------------------------------
def stage_fetch_recent():
    print(f"[*] STAGE 1: Polling MalwareBazaar (selector={SELECTOR})...")

    if not MALWARE_BAZAAR_KEY:
        print("[!] MALWARE_BAZAAR_KEY not set in .env - skipping live fetch.")
        return

    headers = {"Auth-Key": MALWARE_BAZAAR_KEY}
    data = {"query": "get_recent", "selector": SELECTOR}

    try:
        response = requests.post(API_URL, headers=headers, data=data, timeout=30)
        response.raise_for_status()
        result = response.json()
    except Exception as e:
        print(f"[!] Request to MalwareBazaar failed: {_redact(e)}")
        return

    status = result.get("query_status")
    if status == "no_results":
        print("[*] No samples in this window - nothing new to fetch.")
        return
    if status != "ok":
        print(f"[!] MalwareBazaar returned an error status: {status}")
        return

    batch = []
    for sample in result.get("data", []):
        sha256 = sample.get("sha256_hash")
        if not sha256:
            continue
        batch.append((sha256, sample.get("signature"), sample.get("reporter")))

    added, skipped = _write_batch(batch)
    print(f"[+] Stage 1 done. {added} new hash(es) added, {skipped} already present.")


# ---------------------------------------------------------------------
# STAGE 2 - BULK: full.csv
# ---------------------------------------------------------------------
def _strip_comments(file_stream):
    """Drops abuse.ch's leading '#' comment lines and un-comments the
    real header row."""
    for line in file_stream:
        if line.startswith('# "first_seen_utc"'):
            yield line.replace('# ', '', 1)
        elif line.startswith('#'):
            continue
        else:
            yield line


def stage_load_csv():
    print(f"[*] STAGE 2: Loading bulk CSV from {CSV_PATH}...")

    if not os.path.exists(CSV_PATH):
        print(f"[!] {CSV_PATH} not found. Export your MalwareBazaar full "
              f"dump there first, then re-run this script.")
        return

    added_total = 0
    skipped_total = 0
    batch = []

    with open(CSV_PATH, newline='', encoding="utf-8") as f:
        clean_stream = _strip_comments(f)

        # skipinitialspace=True makes the csv module recognize the opening
        # quote even though fields are separated by ", " (comma+space).
        reader = csv.DictReader(clean_stream, skipinitialspace=True)

        for row in tqdm(reader, desc="Ingesting Hashes"):
            sha256 = (row.get("sha256_hash") or "").strip()
            if not sha256:
                continue
            batch.append((sha256, row.get("signature"), row.get("reporter")))

            if len(batch) >= BATCH_SIZE:
                added, skipped = _write_batch(batch)
                added_total += added
                skipped_total += skipped
                batch = []

    added, skipped = _write_batch(batch)
    added_total += added
    skipped_total += skipped

    print(f"[+] Stage 2 done. {added_total} new hash(es) loaded, {skipped_total} already present.")


# ---------------------------------------------------------------------
# STAGE 3 - VERIFY (optional sanity check)
# ---------------------------------------------------------------------
def stage_verify():
    print("[*] STAGE 3: Verifying Redis consistency...")
    total_keys = r.dbsize()
    hash_set_size = r.scard("malware:hashes")
    known_bad_size = r.hlen("known_bad_hashes")
    expected = hash_set_size + 2

    print(f"    DBSIZE: {total_keys} | malware:hashes: {hash_set_size} | "
          f"known_bad_hashes: {known_bad_size} | expected: {expected}")

    if total_keys != expected:
        print("    [!] DBSIZE mismatch - possible orphaned/missing keys.")
    if hash_set_size != known_bad_size:
        print("    [!] malware:hashes and known_bad_hashes counts differ.")
    if total_keys == expected and hash_set_size == known_bad_size:
        print("    [+] Consistent - no duplicates, no orphaned keys.")


if __name__ == "__main__":
    print("=" * 60)
    print("   THREAT INTEL SYNC")
    print("=" * 60)
    stage_bootstrap_csv()
    stage_fetch_recent()
    stage_load_csv()
    stage_verify()